### ISSUE TITLE
Paginator cache will always miss unless in the same runtime

### ISSUE THREAD

**Issue by awartoft** [zendframework/zend-paginator#1]
The following two methods are used to generate the cacheId for getting and setting the cached items.
Problem is that `spl_object_hash` in `_getCacheInternalId` will change after every runtime, thus nothing can ever be retrieved from the cache. 

``` php

    /**
     * Makes an Id for the cache
     * Depends on the adapter object and the page number
     *
     * Used to store item in cache from that Paginator instance
     *  and that current page
     *
     * @param int $page
     * @return string
     */
    protected function _getCacheId($page = null)
    {
        if ($page === null) {
            $page = $this->getCurrentPageNumber();
        }
        return self::CACHE_TAG_PREFIX . $page . '_' . $this->_getCacheInternalId();
    }

    /**
     * Get the internal cache id
     * Depends on the adapter and the item count per page
     *
     * Used to tag that unique Paginator instance in cache
     *
     * @return string
     */
    protected function _getCacheInternalId()
    {
        return md5(serialize(array(
            spl_object_hash($this->getAdapter()),
            $this->getItemCountPerPage()
        )));
    }
```

According to git blame https://github.com/zendframework/zend-paginator/commit/9e2a8f75db0695aa75648a31030861ee467092ed#diff-b7dae88f55a82631386bada74d3d1e9fL989 the previous method looked like this.

``` php
protected function _getCacheInternalId()            
{
    return md5(serialize($this->getAdapter()) . $this->getItemCountPerPage());
}
```

I'm not sure why this was changed, since doing it this way we could always implement `Serializable` on the adapter and return the relevant parts of the adapter to serialize on.

**Comment by GeeH** [comment]
MD5 is bad... mmmkay!

**Comment by awartoft** [comment]
@GeeH useful as always :angry:

**Comment by samsonasik** [comment]
@macnibblet how about rollback to old way without `spl_object_hash` as know this is not work anymore?

**Comment by sasezaki** [comment]
cache issue seems fixed in zf1 with ZF-6989 
http://framework.zend.com/issues/browse/ZF-6989

I remembered that some zf1 fix is not merged into zf2.
(this is my tracking zf1-zf2 merge status list https://github.com/sasezaki/zf-merge-status/blob/master/result_output/latest_not_merged.md )

**Comment by sasezaki** [comment]
..sorry, above my comment is not related to `spl_object_hash` change

**Comment by samsonasik** [comment]
@macnibblet I've created PR #24 for it.

**Comment by divix1988** [comment]
It's almost end of 2016 (so nearly 2 years) and taking into account that this issue still persists in ZF3, I just can't believe that this wasn't fixed yet? This is EXACTLY why Zend has lost most of their community to the favor of Laravel and Symfony. What a shame from Zend support!

Anywho.., back to the issue.

@macnibblet As you noticed atm you can't serialize PDO instance, however, the other clever way of representing instance of a class is using **get_object_vars()** function, the code below works just fine for persistence cache:

``` php
    protected function _getCacheInternalId()
    {
         return md5(
             json_encode(
                 get_object_vars($this->getAdapter())
             ) . $this->getItemCountPerPage()
         );
    }
```

**Comment by weierophinney** [comment]
@divix1988 I understand your frustration, but please be aware that this is a community project, and issues are reviewed and merged as folks have time. It's not just Zend support (which is a smaller team than you might expect). Additionally, if you look at the fix in #24, there are issues with the implementation that need to be addressed, for which nobody has proposed a solution. If you have one, please feel free to submit a pull request and ping me to review it.

**Comment by divix1988** [comment]
@weierophinney if Zend support team is too small then it needs expanding.. I agree that this is a community project, but you need to support first devs in order to encourage those devs to spread your and then their knowledge to others. I am sorry but 15 months to get a solution on official GIT page is waaaay to long, I hope you agree on that aspect at least.

Anyway, here is a pull request: [30](https://github.com/zendframework/zend-paginator/pull/30), I have mentioned you in it too, so you should get notification.

**Comment by weierophinney** [comment]
While I agree with everything you say, it's not as easy as just saying
"expand the team" - I really wish it was, but there's a lot that goes into
that, particularly when the product does not have direct revenue. Expanding
the community review team is ongoing, but people come and go. It's a tough
problem, unfortunately.

I'll take a look at your pull request tomorrow; thanks!

**Comment by divix1988** [comment]
If you are still looking for community review team then I'm volunteering. I will be deving around ZF3 for next at least 6 months (and hopefully more) time, cause I am writing a Polish book about it  (will be published by Helion.pl).  
Is there any official place to sign-in?

**Comment by daohung2u** [comment]
Write a new class extends \Zend\Paginator\Paginator 
write function overwrite function _getCacheInternalId(), 
write new method for get/set paginatorKey
`
namespace  Libraries\Paginator;
class Paginator extends \Zend\Paginator\Paginator {

    function __construct($adapter) {
        parent::__construct($adapter);
    }

    /**
     * Get the internal cache id
     * Depends on the adapter and the item count per page
     *
     * Used to tag that unique Paginator instance in cache
     *
     * @return string
     */
    final protected function _getCacheInternalId() {
        return md5(serialize(array(
            $this->getPaginatorKey(),
            $this->getItemCountPerPage()
        )));
    }

    private $paginatorKey;

    function setPaginatorKeyForCache($key) {
        $this->paginatorKey = md5($key);
    }

    function getPaginatorKey() {
        return $this->paginatorKey;
    }

}`

use 

`$paginator= \Libraries\Paginator($dbSelect);
$paginator->setCache($fileSystemCache);
$paginator->setCacheEnabled(true);
$paginator->getItemsByPage(1);
$paginator->setPaginatorKeyForCache(__FUNCTION__ . 'paginatorKey');`
