### ISSUE TITLE
Update DbTableGateway typehints

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-paginator#27]
Per [this thread on zf-apigility](https://github.com/zfcampus/zf-apigility/pull/169#discussion_r72506560), the `DbTableGateway` constructor currently requires a concrete `Zend\Db\TableGateway\TableGateway` instance, but should likely accept `TableGatewayInterface` instead. This would be a type loosening, which does not pose a BC break, but which would simplify mocking, and allow for alternate implementations when desired.

**Comment by samsonasik** [comment]
@weierophinney I've created PR https://github.com/zendframework/zend-paginator/pull/32 for it

**Comment by froschdesign** [comment]
For version 2 of zend-paginator and zend-db we will accept #32. But for a future version the typehint must be an interface.
