### ISSUE TITLE
Can paginator be configured to use wrap-around paging?

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/zend-paginator#36]
Is there a way to configure paginator to wrap-around pages?

For example, I am on the 1st page, and I click `previous`, I want to end up at the last page.
Or I'm on the last page and I click `next`, I want to end up at the first page.

Currently using code below creates `null` for `$this->previous`on first page:

    $this->url($this->route, ['page' => $this->previous])

when for wrap-around paging it would be assigned value of `$this->last`

**Comment by froschdesign** [comment]
@dennis-fedco 
Quite simple, because all variables are available in a partial script:

```php
if ($pageCount === $current) {
    echo $this->url($route, ['page' => 1]);
}

if ($current === 1) {
    echo $this->url($route, ['page' => $pageCount]);
}
```

https://docs.zendframework.com/zend-paginator/usage/#rlisting-of-properties
