### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-paginator#40]
@weierophinney 
Please update also the repository description.

We have:

- composer.json: "zend-paginator is a flexible component for paginating collections of data and presenting that data to users."
- Documentation: "Paginate collections of data from arbitrary sources."
- Current repository description: "Paginator component from Zend Framework"

It's your choice! 😉

**Comment by weierophinney** [comment]
Done! I used the one from the documentation. I also updated the repository URL to point to docs.zendframework.com.
